config:
  ts-beszel-serve:
    content: |
      {"TCP":{"443":{"HTTPS":true}},
      "Web":{"$${TS_CERT_DOMAIN}:443":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:8090"}}}},
      "AllowFunnel":{"$${TS_CERT_DOMAIN}:443":false}}
services:
  ts-beszel-hub:
    image: tailscale/tailscale:latest
    container_name: ts-beszel-hub
    hostname: beszel
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags:container
      - TS_SERVE_CONFIG=/config/beszel-hub.json
      - TS_STATE_DIR=/var/lib/tailscale
    configs:
      - source: mealie-ts-serve
        target: /config/serve.json
    volumes:
      - tailscale/state:/var/lib/tailscale
    restart: unless-stopped
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel-hub
    network_mode: service:ts-beszel-hub
    depends_on:
    - ts-beszel-hub
    volumes:
      - beszel-data:/beszel_data
    restart: unless-stopped
