configs:
  mealie-ts-serve:
    content: |
      {"TCP":{"443":{"HTTPS":true}},
      "Web":{"$${TS_CERT_DOMAIN}:443":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:9000"}}}},
      "AllowFunnel":{"$${TS_CERT_DOMAIN}:443":false}}
services:
  mealie-ts:
    image: tailscale/tailscale:latest
    hostname: mealie
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_USERSPACE=true
    configs:
      - source: mealie-ts-serve
        target: /config/serve.json
    volumes:
      - /home/docker-admin/appdata/mealie/tailscale/state:/var/lib/tailscale
    restart: unless-stopped
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.8.0
    container_name: mealie
    restart: unless-stopped
    network_mode: service:mealie-ts
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      -  /home/docker-admin/appdata/mealie/app:/app/data/
    environment:
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
      BASE_URL: ${FQDN}
      OPENAI_API_KEY: ${OPENAPI_API_KEY}
volumes:
  mealie_volume:
